# Attempt to preload modules via Dockerfile
Image:
  file: .gitpod.Dockerfile


# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script', pip install pandas, pip intall pyautogui, pip install pywin32
    command: echo 'start script'


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
